spring:
    datasource:
        url: jdbc:mysql://mysql.ca3zw9ojro1a.rds.cn-northwest-1.amazonaws.com.cn/test?useSSL=false
        username: root
        password: qw3erTYU

mybatis:
    type-aliases-package: fun.xruo.lle.*.pojo
    mapper-locations: classpath*:/templates/*.xml