spring:
    datasource:
        url: jdbc:mysql://mysql.ca3zw9ojro1a.rds.cn-northwest-1.amazonaws.com.cn:3306/lle
        username: lle
        password: lle
mybatis:
    type-aliases-package: fun.xruo.lle.*.pojo
    mapper-locations: classpath*:/fun/xruo/lle/**/*.xml

logging:
    level:
        fun.xruo.lle: trace

my:
    framework:
        artifact: fun.xruo
        group: lle
        module: sys