spring:
    datasource:
        url: jdbc:mysql://localhost/dev?useSSL=false
        username: root
        password: 1234
#
#mybatis:
#    type-aliases-package: fun.xruo.lle.*.pojo
#    mapper-locations: classpath*:/fun/xruo/lle/**/*.xml

logging:
    level:
        fun.xruo.lle: trace

my:
    framework:
        artifact: fun.xruo
        group: lle
        module: sys