spring:
    datasource:
        url: jdbc:mysql://localhost/test?useSSL=false
        username: root
        password: 123456

mybatis:
    type-aliases-package: fun.xruo.lle.*.pojo
    mapper-locations: classpath*:/fun/xruo/lle/**/*.xml

my:
    framework:
        artifact: fun.xruo
        group: lle
        module: sys